- .pre-commit-config.yaml
- docs/index.md
- extras_require.txt
- mkdocs.yml
- mypy.ini
- scripts/i2i/translate_image.py
- scripts/map_labels.py
- scripts/run_monai_unet.py
- src/segmantic/__init__.py
- src/segmantic/i2i/translate.py
- src/segmantic/prepro/core.py
- src/segmantic/prepro/extract_cyclegan.py
- src/segmantic/prepro/extract_pix2pix.py
- src/segmantic/prepro/labels.py
- src/segmantic/seg/evaluation.py
- src/segmantic/seg/monai_unet.py
- src/segmantic/seg/utils.py
- src/segmantic/seg/visualization.py
- tests/fixture.py
- tests/prepro/test_core.py
- tests/prepro/test_labels.py
- tests/seg/test_evaluation.py
- add tests for code in modules
- fix bugs, e.g. in `extract_slices`, `resample`
- move evaluation code to separate module
- add `hausdorff_distance` evaluation metric
- use `typer` instead of `argparse`
- use `pathlib.Path` instead of `str` to annotate paths
- na
> ✨ 📝: Evaluation metrics

- scripts/run_monai_unet.py
- src/segmantic/i2i/translate.py
- src/segmantic/prepro/extract_cyclegan.py
- src/segmantic/prepro/extract_pix2pix.py
- src/segmantic/prepro/labels.py
- src/segmantic/prepro/make_mixed_modal_dataset.py
- src/segmantic/seg/evaluation.py
- src/segmantic/seg/monai_unet.py
- src/segmantic/seg/visualization.py
cleanup use of 
- `os.path`, `os.listdir`, `str.replace` for paths
avoid importing segmantic inside package, i.e. use relative paths instead of `import segmantic`
> ♻️ cleanup use of os.path, listdir, str.replace for paths

- mypy.ini
- scripts/i2i/translate_image.py
- scripts/run_monai_unet.py
- setup.py
- src/segmantic/i2i/translate.py
- src/segmantic/prepro/__init__.py
- src/segmantic/prepro/core.py
- src/segmantic/seg/dataset.py
- src/segmantic/seg/monai_unet.py
- tests/fixture.py
- tests/i2i/test_translate.py
- tests/prepro/test_core.py
- tests/prepro/test_image_order.py
Add functionality to tile image into patches, e.g. to use pix2pix trained on fixed size (256x256)
- adding image-to-image translation functionality
- run `pytest tests`
- given a trained pix2pix model run: `python scripts\i2i\translate_image.py -m latest_net_G.pth -i T1.nii.gz -o synCT.nii.gz --axis 2 --gpu-ids 0`
> WIP: ✨Tiling image into patches

- src/segmantic/seg/monai_unet.py
load legacy settings only if the file exists.
print message that legacy json file was used to get settings.
> 🐛 load legacy settings only if the file exists

- src/segmantic/seg/monai_unet.py
- add load_from_checkpoint
- add intensity and spatial augmentation
na
please run training with restart, i.e. in the train-config mode set the model_file
>   ✨ add load_from_checkpoint and augmentation

- src/segmantic/seg/dataset.py
ensure we have at least one validation dataset
> 🐛: ensure we have at least one validation dataset

- .github/workflows/deploy_and_test.yml
- README.md
- pyproject.toml
- requirements/generic.txt
- src/segmantic/seg/monai_unet.py
- The version of ITK in generix.txt did not work with monai.
- The version of typer (0.4.0) did not work with the version of click
None
> 🐛fix requirements

- requirements/generic.txt
fix vulnerability for version of pytorch-lightning
> ⬆️ fix vulnerability

- .github/workflows/deploy_and_test.yml
- pyproject.toml
- src/segmantic/commands/monai_unet_cli.py
- src/segmantic/seg/dataset.py
- src/segmantic/seg/evaluation.py
- src/segmantic/seg/monai_unet.py
- src/segmantic/seg/visualization.py
- tests/conftest.py
- tests/i2i/test_translate.py
- tests/prepro/test_core.py
- tests/prepro/test_labels.py
- tests/seg/test_evaluation.py
Running `python scripts\run_monai_unet.py train-config -c C:\Path\To\config.json` was failing (on Windows) because path from json file was not casted to `pathlib.Path`.
Run unet `train-config` on Windows.
> 🐛 fix type comparison for casting to path

- src/segmantic/seg/monai_unet.py
fix predict:
- `to_one_hot` was not returning the tensor
>  🐛 fix predict

- .pre-commit-config.yaml
- scripts/generate_dataset.py
- src/segmantic/seg/monai_unet.py
fix intensity augmentation training
- recent version of monai (0.9) seems to introduce something that breaks the pytorch lightning training because of incompatible tensor types ([issue 4537](https://github.com/Project-MONAI/MONAI/issues/4537))
- fixed use of `RandCropByLabelClassesd` to not provide an `image_key` (we already crop foreground)
> 🐛 fix intensity augmentation training

- .coveragerc
- .github/workflows/deploy_and_test.yml
- .pre-commit-config.yaml
- README.md
- pyproject.toml
- add new pre-commit hook: [pycln](https://github.com/hadialqattan/pycln)
- add coverage reporting using [pytest-cov](https://github.com/pytest-dev/pytest-cov)
>  ⬆️ Upgrade hooks

- src/segmantic/commands/monai_unet_cli.py
- src/segmantic/seg/monai_unet.py
- tests/seg/test_unet.py
- fix predict, `net.create_transforms` was called
- minor clean-up evaluation (https://github.com/dyollb/segmantic/issues/33)
> 🐛fix predict, minor clean-up evaluation

- pyproject.toml
- src/segmantic/i2i/translate.py
- src/segmantic/prepro/core.py
- src/segmantic/prepro/extract_cyclegan.py
- src/segmantic/prepro/extract_pix2pix.py
- src/segmantic/prepro/modality.py
- src/segmantic/seg/evaluation.py
- src/segmantic/seg/monai_unet.py
- tests/util/test_cli.py
Added warnings for mypy, e.g. 
- warn_return_any
- warn_redundant_casts
Refactored type vars for generic functions that take image or ndarray.
> ♻️ additional mypy warnings

- scripts/check_masks.py
- scripts/generate_dataset.py
- src/segmantic/commands/monai_unet_cli.py
- src/segmantic/seg/dataset.py
- src/segmantic/seg/monai_unet.py
- src/segmantic/seg/visualization.py
- tests/seg/test_dataset.py
- 🚑️ fix RandCropByLabelClasses args
- ⚗️ changed order of augmentation
-  ⚗️ added RandBiasField
> 🚑️ fix RandCropByLabelClasses args

- pyproject.toml
- scripts/image_processing.py
- src/segmantic/commands/image_command.py
- src/segmantic/commands/monai_unet_cli.py
- src/segmantic/prepro/modality.py
- src/segmantic/seg/nyul_normalize.py
- src/segmantic/util/cli.py
- src/segmantic/util/json.py
- tests/seg/test_normalize.py
- ✨add n4 bias correction for MRI
- ⚗️ add draft nyul normalizer to plug into MONAI
> ✨add n4 bias correction,  ⚗️ add draft nyul normalizer

- README.md
- docs/index.md
📝  inform gh which syntax highlighting to use
> 📝  inform gh which syntax highlighting to use

- pyproject.toml
- src/segmantic/i2i/pix2pix_cyclegan/models/__init__.py
- src/segmantic/seg/monai_unet.py
- use ITKWriter 
- use `monai.data.DataLoader` instead of `torch.utils.data.DataLoader`
- fix mypy errors due to new versions of monai, etc.
> 🐛 use monai DataLoader

- .github/workflows/deploy_and_test.yml
- .github/workflows/lint.yml
- pyproject.toml
- setup.py
- src/segmantic/seg/monai_unet.py
fix broken cross-validation.
Fixes issues
- #59 
- #60
> 🐛 Fix Dataset/input-output dir conflict

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/deploy_and_test.yml
- .pre-commit-config.yaml
- codecov.yml
- pyproject.toml
- requirements/cu111.txt
- requirements/cu113.txt
- requirements/docs.txt
- requirements/generic.txt
- scripts/check_masks.py
- scripts/evaluate_segmentations.py
- src/segmantic/detect/transforms.py
- src/segmantic/seg/dataset.py
- src/segmantic/seg/monai_unet.py
- src/segmantic/seg/nyul_normalize.py
- tests/image/test_image.py
- tests/image/test_image_order.py
- tests/image/test_labels.py
- tests/seg/test_unet.py
- add [ruff](https://github.com/astral-sh/ruff) pre-commit
- update pre-commit hooks
- run all files
- remove py 3.7 support
- add python 3.11 support
> ♻️ update hooks, add ruff, add py11 support
